### ISSUE TITLE
deferentially expressed analysis on the RNA data from COAD using GEO

### ISSUE THREAD

**Issue by Rahel14350** [ibsquare/MoonlightR#1]
Dear all,
I want to do deferentially expressed analysis on the RNA data from COAD using GEO and also TCGA data. I have this error with GEO data:
###
data(GEO_TCGAtab)
DataAnalysisGEO<- "../GEO_dataset/"
i<-4
cancer <- GEO_TCGAtab$Cancer[i]
cancerGEO <- GEO_TCGAtab$Dataset[i]
cancerPLT <-GEO_TCGAtab$Platform[i]
fileCancerGEO <- paste0(cancer,"_GEO_",cancerGEO,"_",cancerPLT, ".RData")
dataFilt <- getDataGEO(TCGAtumor = cancer)
GEOdegs <- DPA(dataConsortium = "GEO",
               gset = dataFilt ,
               colDescription = "title",
               samplesType  = c(GEO_TCGAtab$GEO_Normal[i],
                                GEO_TCGAtab$GEO_Tumor[i]), fdr.cut = 0.01,logFC.cut = 1,
               gsetFile = paste0(DataAnalysisGEO,fileCancerGEO))
Error in eval(ej, envir = levelsenv) : object 'xContrast' not found
###
Can you please help me here (there is the same error with example from Moonlight)? and is it possible to combine GEO and TCGA data together and do DPA part?
Kind regards,
Rahel

**Comment by elenapapaleo** [comment]
We apologize for not looking into this. Did you find a solution? or the question is still relevant for you?
