### ISSUE TITLE
Moonlight installation Rstudio

### ISSUE THREAD

**Issue by annarerra** [ibsquare/MoonlightR#15]
Hello,

I tried to Install moonlight in my Rstudio (2022.02.0 Build 443, R version: 4.1.2) but there is a package that is possing a problem.
![image](https://user-images.githubusercontent.com/74925521/175920657-8d26162c-fd63-42a5-ad24-beaaa83cfd2a.png)

I tried to intall **tcltk** by myself but nothing and then i found this online: https://support.rstudio.com/hc/en-us/articles/226302647-Is-the-tcl-tk-package-supported-within-RStudio-Workbench-RStudio-Server-

I would appreciate any help :)

**Comment by mtiberti** [comment]
Hi,
sorry for the late reply. Judging from #16 you might have managed to solve this already?
Anyhow, looks like you are missing the TCL Tk libraries in your system - for instance on Ubuntu you probably need to install the `libtcl8.5` package. Let me know if this helps

**Comment by elenapapaleo** [comment]
closing since it seems to be solved
