### ISSUE TITLE
WARNINGs on CHECK in BioC 3.17

### ISSUE THREAD

**Issue by mtiberti** [ibsquare/MoonlightR#19]
In the [automated builder reports](https://master.bioconductor.org/checkResults/3.17/bioc-LATEST/MoonlightR/merida1-checksrc.html) we get some warnings in the `CHECK` test:

```
Found the following significant warnings:
  Note: possible error in 'GDCquery(project = CancerProject, ': unused arguments (file.type = "results", legacy = TRUE) 
  Note: possible error in 'GDCquery(project = CancerProject, ': unused argument (legacy = TRUE) 
```

these also show up in the installation as Notes:

```
Note: possible error in 'GDCquery(project = CancerProject, ': unused arguments (file.type = "results", legacy = TRUE) 
Note: possible error in 'GDCquery(project = CancerProject, ': unused arguments (file.type = "results", legacy = TRUE) 
Note: possible error in 'GDCquery(project = CancerProject, ': unused arguments (file.type = "results", legacy = TRUE) 
Note: possible error in 'GDCquery(project = CancerProject, ': unused argument (legacy = TRUE) 
Note: possible error in 'GDCquery(project = CancerProject, ': unused argument (legacy = TRUE) 
```

it just might be enough to remove the offending arguments (after checking if this has consequences on the data we get)

**Comment by tiagochst** [comment]
The legacy database was shutdown by GDC. There is no access to the legacy data anymore. If `legacy = TRUE` was used the code needs be reviewed.

**Comment by mtiberti** [comment]
Thank you @tiagochst - agreed we need to double check that
