### ISSUE TITLE
ERROR in CHECK in Bioc 3.17

### ISSUE THREAD

**Issue by mtiberti** [ibsquare/MoonlightR#20]
We have an error during CHECK for Linux:

```
> dataDEGs <- DPA(dataFilt = dataFilt, dataType = "Gene expression")
Error: edgeR package is needed for this function to work. Please install it.
Execution halted
```

This might be due to the fact that `edgeR` is also failing on Linux. However I'm not really sure why it is not one of our requirements if we then use it?

**Comment by tiagochst** [comment]
Very likely `edgeR` is being required by `TCGAbiolinks` functions.
Also, `edgeR` is only a suggested package by `TCGAbiolinks`, for that reason it is not installed by default.

**Comment by mtiberti** [comment]
thanks @tiagochst - I see - then maybe it makes sense to have it as a dependency in MoonlightR? So we avoid that error. Assuming it can be installed.

**Comment by tiagochst** [comment]
This error should not happen in Bioconductor since `edgeR` would be in the system and loaded, unless edgeR is also failing in Bioconductor.


I am guessing  the linux CHECK is performed locally.
If you install TCGAbioliolinks with `dependencies=TRUE`, edgeR would be installed and there will be no error.

**Comment by mtiberti** [comment]
I see - fact is edgeR is failing on Bioconductor (Linux) so that's why MoonlightR is failing. Do you think we should just wait for them to fix the edgeR package? One of their test is failing

**Comment by tiagochst** [comment]
It seems `edgeR` is falling only on windows because  `statmod package required but is not installed` in the windows machine. I would write an email to Bioconductor team since it does not look like it is a `edgeR` issue.

**Comment by mtiberti** [comment]
oh yes that is the reason indeed, but it seems to me that the fail is still on Linux (nebbiolo1) and not Windows

**Comment by mtiberti** [comment]
`edgeR` is all green now, but we are still failing. I think we should just add `edgeR` as a dependency in MoonlightR
