### ISSUE TITLE
I want to identify the TSG and OCG in two TCGA datasets i.e, COAD & READ

### ISSUE THREAD

**Issue by Pravithaks** [ibsquare/MoonlightR#21]
When I tried to run the moonlight pipeline, it throws a error:
Error in GDCquery(project = CancerProject, data.category = "Gene expression",  : 
  unused arguments (file.type = "results", legacy = TRUE)
  please help!

**Comment by mona-n** [comment]
Hi, thanks for using Moonlight and letting us know about the errors you get! We are working on solving this through the open PRs and hopefully it should be resolved soon

**Comment by mtiberti** [comment]
hi, @Pravithaks we solved this in PR #23 and propagated the changes to the Bioconductor repository - if you try and reinstall the package from Bioconductor, that should be working now. I'm closing this for now, but let's reopen it if you find other issues associated with this
